# -*- coding: utf-8 -*-
"""tweet_DB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OAHVOnEm8GajCE7IQ7osfnAs2NQZlfeX
"""

import tweepy
from tweepy import OAuthHandler, API
import pandas as pd
import datetime

"""API key 입력"""

CONSUMER_KEY = 'your consumer key'
CONSUMER_SECRET = 'your consumer secret key'
ACCESS_TOKEN = 'your access_token'
ACCESS_TOKEN_SECRET = 'your access token secret key'

"""API 접근"""

auth = OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)

api = tweepy.API(auth, wait_on_rate_limit = True)

"""트윗에서 정보 추출"""

#트윗 가져오는 함수 parameter는 searched_tweet
def TweetToList(twitterList):
  res_list = [] #딕셔너리의 리스트
  for t in twitterList:
    #metadata
    id_str = t.id_str #해당 글의 고유한 아이디임
    user_name = t.author.screen_name
    created_at = t.created_at.strftime("%Y-%m-%d %H:%M:%S")
    text = t.text
    source = t.source

    #time-series data
    retweet = t.retweet_count
    favorite = t.favorite_count
    
    tmp_dic = {'id_str':id_str, 'user_name':user_name, 'created_at': created_at, 'text': text,
               'retweet': retweet, 'favorite':favorite, 'source': source}
    res_list.append(tmp_dic)
  return res_list

"""오늘 날짜 알아내기"""

dt2 = datetime.datetime.now()
dt1 = dt2 - datetime.timedelta(days = 1)
dt2 = dt2.strftime("%Y-%m-%d")
dt1 = dt1.strftime("%Y-%m-%d")

"""raw tweet data 가져와 저장"""

location = "%s,%s,%s" % ("34,95","128.25","1000km")
keyword = "조국 AND 문재인"
searched_tweets = []  #검색된 트윗 저장 위한 리스트

cursor = tweepy.Cursor(api.search,
                      q = keyword,
                      since = dt1,
                      until = dt2,
                      count = 100)

for t in cursor.items():
  searched_tweets.append(t)

today_tweets = TweetToList(searched_tweets)

for i in range(0,len(today_tweets)):
  today_tweets[i]['text'] = today_tweets[i]['text'].replace("\n", " ")

"""똑같은 내용 중복 제거"""

remove_dup = list({a['text']: a for a in today_tweets}.values())

print(len(today_tweets))
print(len(remove_dup))

for i in remove_dup:
  print(i)

"""mysql로 저장"""


|import pymysql
conn = pymysql.connect(host = "203.252.196.68",
                       user = 'db1714670', passwd = 'stat1234', db = 'sql1714670')
cur = conn.cursor()

#query1 = """
#CREATE TABLE TweetMetadata (
#    id BIGINT(7) NOT NULL AUTO_INCREMENT,
#    ID_str VARCHAR(30),
#    UserName VARCHAR(20),
#    CreatedTime DATETIME,
#    Text VARCHAR(1000),
#    Source VARCHAR(30),
#    PRIMARY KEY(id,ID_str) )
#    CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;
#"""
#cur.execute(query1)

#query2 = """
#CREATE TABLE TweetTSdata (
#    ID_str VARCHAR(30),
#    date_of_crawl DATETIME NOT NULL DEFAULT NOW(),
#    retweet BIGINT(15),
#    likes BIGINT(10),
#    PRIMARY KEY(ID_str))
#    CHARSET = utf8mb4;
#"""
#cur.execute(query2)

for tweet in remove_dup:
  query3 = """INSERT INTO TweetMetadata (ID_str,UserName,CreatedTime,Text,Source)
  VALUES(%s,%s,%s,%s,%s)
  """
  cur.execute(query3,(tweet['id_str'],tweet['user_name'], tweet['created_at'], tweet['text'], tweet['source']))

  query4 ="""INSERT INTO TweetTSdata (ID_str,retweet,likes)
  VALUES(%s,%s,%s)
  """ 
  cur.execute(query4,(tweet['id_str'],tweet['retweet'],tweet['favorite']))

conn.commit()
cur.close()
conn.close()